language:
  cpp
compiler:
  - gcc
before_install:
  sudo apt-get update
install:
  sudo apt-get install libhdf5-serial-dev libboost-dev libboost-thread-dev
script:
  autoreconf -i && ./configure && make
