COMEDI_DEVICE="/dev/comedi0"
AI_CONVERSION_FACTOR=100
AO_CONVERSION_FACTOR=0.001
RANGE="[-10,+10]"
AI_SUBDEVICE=0
AI_CHANNEL=0
AO_SUBDEVICE=1
AO_CHANNEL=0
INPUT_UNITS="mV"
OUTPUT_UNITS="pA"
GROUND_REFERENCE="GRSE"
export AI_CONVERSION_FACTOR
export AO_CONVERSION_FACTOR
export RANGE
export AI_SUBDEVICE
export AI_CHANNEL
export AO_SUBDEVICE
export AO_CHANNEL
export INPUT_UNITS
export OUTPUT_UNITS
export GROUND_REFERENCE
