AI_CONVERSION_FACTOR=100
AO_CONVERSION_FACTOR=0.001
AI_SUBDEVICE=0
AO_SUBDEVICE=1
INPUT_UNITS="mV"
OUTPUT_UNITS="pA"
GROUND_REF="GRSE"

export AI_CONVERSION_FACTOR
export AO_CONVERSION_FACTOR
export AI_SUBDEVICE
export AO_SUBDEVICE
export INPUT_UNITS
export OUTPUT_UNITS
export GROUND_REF

